allowBuilds:
  '@playwright/browser-chromium': true
  '@vscode/vsce-sign': false
  esbuild: true
  keytar: false
  lefthook: true
enablePrePostScripts: true
minimumReleaseAge: 4320
overrides:
  diff: ^8.0.4
  nanoid: ^3.3.18
  serialize-javascript: ^7.0.6
saveExact: true
strictPeerDependencies: true
